PULP_APP = runtime_output_axi
PULP_APP_FC_SRCS = runtime_output_axi.c
PULP_APP_HOST_SRCS = runtime_output_axi.c
PULP_CFLAGS = -O3 -g -I../runtime_shared/include

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk

