// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module safety_soc_ctrl_icache_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 6,
  parameter int unsigned BootAddrDefault = 32'h0
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output safety_soc_ctrl_icache_reg_pkg::safety_soc_ctrl_icache_reg2hw_t reg2hw, // Write
  input  safety_soc_ctrl_icache_reg_pkg::safety_soc_ctrl_icache_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import safety_soc_ctrl_icache_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] bootaddr_qs;
  logic [31:0] bootaddr_wd;
  logic bootaddr_we;
  logic fetchen_qs;
  logic fetchen_wd;
  logic fetchen_we;
  logic [31:0] corestatus_qs;
  logic [31:0] corestatus_wd;
  logic corestatus_we;
  logic [1:0] bootmode_qs;
  logic [1:0] bootmode_wd;
  logic bootmode_we;
  logic icache_enable_prefetch_qs;
  logic icache_enable_prefetch_wd;
  logic icache_enable_prefetch_we;
  logic icache_flush_qs;
  logic icache_flush_wd;
  logic icache_flush_we;
  logic icache_flush_re;
  logic icache_perfctr_ctrl_enable_qs;
  logic icache_perfctr_ctrl_enable_wd;
  logic icache_perfctr_ctrl_enable_we;
  logic icache_perfctr_ctrl_clear_all_qs;
  logic icache_perfctr_ctrl_clear_all_wd;
  logic icache_perfctr_ctrl_clear_all_we;
  logic [31:0] counters_0_qs;
  logic [31:0] counters_0_wd;
  logic counters_0_we;
  logic [31:0] counters_1_qs;
  logic [31:0] counters_1_wd;
  logic counters_1_we;
  logic [31:0] counters_2_qs;
  logic [31:0] counters_2_wd;
  logic counters_2_we;
  logic [31:0] counters_3_qs;
  logic [31:0] counters_3_wd;
  logic counters_3_we;
  logic [31:0] counters_4_qs;
  logic [31:0] counters_4_wd;
  logic counters_4_we;
  logic [31:0] counters_5_qs;
  logic [31:0] counters_5_wd;
  logic counters_5_we;
  logic [31:0] counters_6_qs;
  logic [31:0] counters_6_wd;
  logic counters_6_we;
  logic [31:0] counters_7_qs;
  logic [31:0] counters_7_wd;
  logic counters_7_we;
  logic [31:0] counters_8_qs;
  logic [31:0] counters_8_wd;
  logic counters_8_we;

  // Register instances
  // R[bootaddr]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (BootAddrDefault)
  ) u_bootaddr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (bootaddr_we),
    .wd     (bootaddr_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.bootaddr.q ),

    // to register interface (read)
    .qs     (bootaddr_qs)
  );


  // R[fetchen]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_fetchen (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (fetchen_we),
    .wd     (fetchen_wd),

    // from internal hardware
    .de     (hw2reg.fetchen.de),
    .d      (hw2reg.fetchen.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.fetchen.q ),

    // to register interface (read)
    .qs     (fetchen_qs)
  );


  // R[corestatus]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_corestatus (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (corestatus_we),
    .wd     (corestatus_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.corestatus.q ),

    // to register interface (read)
    .qs     (corestatus_qs)
  );


  // R[bootmode]: V(False)

  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_bootmode (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (bootmode_we),
    .wd     (bootmode_wd),

    // from internal hardware
    .de     (hw2reg.bootmode.de),
    .d      (hw2reg.bootmode.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.bootmode.q ),

    // to register interface (read)
    .qs     (bootmode_qs)
  );


  // R[icache_enable_prefetch]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_icache_enable_prefetch (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (icache_enable_prefetch_we),
    .wd     (icache_enable_prefetch_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.icache_enable_prefetch.q ),

    // to register interface (read)
    .qs     (icache_enable_prefetch_qs)
  );


  // R[icache_flush]: V(True)

  prim_subreg_ext #(
    .DW    (1)
  ) u_icache_flush (
    .re     (icache_flush_re),
    .we     (icache_flush_we),
    .wd     (icache_flush_wd),
    .d      (hw2reg.icache_flush.d),
    .qre    (),
    .qe     (reg2hw.icache_flush.qe),
    .q      (reg2hw.icache_flush.q ),
    .qs     (icache_flush_qs)
  );


  // R[icache_perfctr_ctrl]: V(False)

  //   F[enable]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_icache_perfctr_ctrl_enable (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (icache_perfctr_ctrl_enable_we),
    .wd     (icache_perfctr_ctrl_enable_wd),

    // from internal hardware
    .de     (hw2reg.icache_perfctr_ctrl.enable.de),
    .d      (hw2reg.icache_perfctr_ctrl.enable.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.icache_perfctr_ctrl.enable.q ),

    // to register interface (read)
    .qs     (icache_perfctr_ctrl_enable_qs)
  );


  //   F[clear_all]: 16:16
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_icache_perfctr_ctrl_clear_all (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (icache_perfctr_ctrl_clear_all_we),
    .wd     (icache_perfctr_ctrl_clear_all_wd),

    // from internal hardware
    .de     (hw2reg.icache_perfctr_ctrl.clear_all.de),
    .d      (hw2reg.icache_perfctr_ctrl.clear_all.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.icache_perfctr_ctrl.clear_all.q ),

    // to register interface (read)
    .qs     (icache_perfctr_ctrl_clear_all_qs)
  );



  // Subregister 0 of Multireg counters
  // R[counters_0]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("W0C"),
    .RESVAL  (32'h0)
  ) u_counters_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (counters_0_we),
    .wd     (counters_0_wd),

    // from internal hardware
    .de     (hw2reg.counters[0].de),
    .d      (hw2reg.counters[0].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.counters[0].q ),

    // to register interface (read)
    .qs     (counters_0_qs)
  );

  // Subregister 1 of Multireg counters
  // R[counters_1]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("W0C"),
    .RESVAL  (32'h0)
  ) u_counters_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (counters_1_we),
    .wd     (counters_1_wd),

    // from internal hardware
    .de     (hw2reg.counters[1].de),
    .d      (hw2reg.counters[1].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.counters[1].q ),

    // to register interface (read)
    .qs     (counters_1_qs)
  );

  // Subregister 2 of Multireg counters
  // R[counters_2]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("W0C"),
    .RESVAL  (32'h0)
  ) u_counters_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (counters_2_we),
    .wd     (counters_2_wd),

    // from internal hardware
    .de     (hw2reg.counters[2].de),
    .d      (hw2reg.counters[2].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.counters[2].q ),

    // to register interface (read)
    .qs     (counters_2_qs)
  );

  // Subregister 3 of Multireg counters
  // R[counters_3]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("W0C"),
    .RESVAL  (32'h0)
  ) u_counters_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (counters_3_we),
    .wd     (counters_3_wd),

    // from internal hardware
    .de     (hw2reg.counters[3].de),
    .d      (hw2reg.counters[3].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.counters[3].q ),

    // to register interface (read)
    .qs     (counters_3_qs)
  );

  // Subregister 4 of Multireg counters
  // R[counters_4]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("W0C"),
    .RESVAL  (32'h0)
  ) u_counters_4 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (counters_4_we),
    .wd     (counters_4_wd),

    // from internal hardware
    .de     (hw2reg.counters[4].de),
    .d      (hw2reg.counters[4].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.counters[4].q ),

    // to register interface (read)
    .qs     (counters_4_qs)
  );

  // Subregister 5 of Multireg counters
  // R[counters_5]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("W0C"),
    .RESVAL  (32'h0)
  ) u_counters_5 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (counters_5_we),
    .wd     (counters_5_wd),

    // from internal hardware
    .de     (hw2reg.counters[5].de),
    .d      (hw2reg.counters[5].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.counters[5].q ),

    // to register interface (read)
    .qs     (counters_5_qs)
  );

  // Subregister 6 of Multireg counters
  // R[counters_6]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("W0C"),
    .RESVAL  (32'h0)
  ) u_counters_6 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (counters_6_we),
    .wd     (counters_6_wd),

    // from internal hardware
    .de     (hw2reg.counters[6].de),
    .d      (hw2reg.counters[6].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.counters[6].q ),

    // to register interface (read)
    .qs     (counters_6_qs)
  );

  // Subregister 7 of Multireg counters
  // R[counters_7]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("W0C"),
    .RESVAL  (32'h0)
  ) u_counters_7 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (counters_7_we),
    .wd     (counters_7_wd),

    // from internal hardware
    .de     (hw2reg.counters[7].de),
    .d      (hw2reg.counters[7].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.counters[7].q ),

    // to register interface (read)
    .qs     (counters_7_qs)
  );

  // Subregister 8 of Multireg counters
  // R[counters_8]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("W0C"),
    .RESVAL  (32'h0)
  ) u_counters_8 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (counters_8_we),
    .wd     (counters_8_wd),

    // from internal hardware
    .de     (hw2reg.counters[8].de),
    .d      (hw2reg.counters[8].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.counters[8].q ),

    // to register interface (read)
    .qs     (counters_8_qs)
  );




  logic [15:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_BOOTADDR_OFFSET);
    addr_hit[ 1] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_FETCHEN_OFFSET);
    addr_hit[ 2] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_CORESTATUS_OFFSET);
    addr_hit[ 3] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_BOOTMODE_OFFSET);
    addr_hit[ 4] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_ICACHE_ENABLE_PREFETCH_OFFSET);
    addr_hit[ 5] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_ICACHE_FLUSH_OFFSET);
    addr_hit[ 6] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_ICACHE_PERFCTR_CTRL_OFFSET);
    addr_hit[ 7] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_COUNTERS_0_OFFSET);
    addr_hit[ 8] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_COUNTERS_1_OFFSET);
    addr_hit[ 9] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_COUNTERS_2_OFFSET);
    addr_hit[10] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_COUNTERS_3_OFFSET);
    addr_hit[11] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_COUNTERS_4_OFFSET);
    addr_hit[12] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_COUNTERS_5_OFFSET);
    addr_hit[13] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_COUNTERS_6_OFFSET);
    addr_hit[14] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_COUNTERS_7_OFFSET);
    addr_hit[15] = (reg_addr == SAFETY_SOC_CTRL_ICACHE_COUNTERS_8_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[14] & ~reg_be))) |
               (addr_hit[15] & (|(SAFETY_SOC_CTRL_ICACHE_PERMIT[15] & ~reg_be)))));
  end

  assign bootaddr_we = addr_hit[0] & reg_we & !reg_error;
  assign bootaddr_wd = reg_wdata[31:0];

  assign fetchen_we = addr_hit[1] & reg_we & !reg_error;
  assign fetchen_wd = reg_wdata[0];

  assign corestatus_we = addr_hit[2] & reg_we & !reg_error;
  assign corestatus_wd = reg_wdata[31:0];

  assign bootmode_we = addr_hit[3] & reg_we & !reg_error;
  assign bootmode_wd = reg_wdata[1:0];

  assign icache_enable_prefetch_we = addr_hit[4] & reg_we & !reg_error;
  assign icache_enable_prefetch_wd = reg_wdata[0];

  assign icache_flush_we = addr_hit[5] & reg_we & !reg_error;
  assign icache_flush_wd = reg_wdata[0];
  assign icache_flush_re = addr_hit[5] & reg_re & !reg_error;

  assign icache_perfctr_ctrl_enable_we = addr_hit[6] & reg_we & !reg_error;
  assign icache_perfctr_ctrl_enable_wd = reg_wdata[0];

  assign icache_perfctr_ctrl_clear_all_we = addr_hit[6] & reg_we & !reg_error;
  assign icache_perfctr_ctrl_clear_all_wd = reg_wdata[16];

  assign counters_0_we = addr_hit[7] & reg_we & !reg_error;
  assign counters_0_wd = reg_wdata[31:0];

  assign counters_1_we = addr_hit[8] & reg_we & !reg_error;
  assign counters_1_wd = reg_wdata[31:0];

  assign counters_2_we = addr_hit[9] & reg_we & !reg_error;
  assign counters_2_wd = reg_wdata[31:0];

  assign counters_3_we = addr_hit[10] & reg_we & !reg_error;
  assign counters_3_wd = reg_wdata[31:0];

  assign counters_4_we = addr_hit[11] & reg_we & !reg_error;
  assign counters_4_wd = reg_wdata[31:0];

  assign counters_5_we = addr_hit[12] & reg_we & !reg_error;
  assign counters_5_wd = reg_wdata[31:0];

  assign counters_6_we = addr_hit[13] & reg_we & !reg_error;
  assign counters_6_wd = reg_wdata[31:0];

  assign counters_7_we = addr_hit[14] & reg_we & !reg_error;
  assign counters_7_wd = reg_wdata[31:0];

  assign counters_8_we = addr_hit[15] & reg_we & !reg_error;
  assign counters_8_wd = reg_wdata[31:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = bootaddr_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = fetchen_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = corestatus_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[1:0] = bootmode_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[0] = icache_enable_prefetch_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[0] = icache_flush_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[0] = icache_perfctr_ctrl_enable_qs;
        reg_rdata_next[16] = icache_perfctr_ctrl_clear_all_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = counters_0_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[31:0] = counters_1_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[31:0] = counters_2_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[31:0] = counters_3_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[31:0] = counters_4_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[31:0] = counters_5_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[31:0] = counters_6_qs;
      end

      addr_hit[14]: begin
        reg_rdata_next[31:0] = counters_7_qs;
      end

      addr_hit[15]: begin
        reg_rdata_next[31:0] = counters_8_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module safety_soc_ctrl_icache_reg_top_intf
#(
  parameter int AW = 6,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output safety_soc_ctrl_icache_reg_pkg::safety_soc_ctrl_icache_reg2hw_t reg2hw, // Write
  input  safety_soc_ctrl_icache_reg_pkg::safety_soc_ctrl_icache_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  safety_soc_ctrl_icache_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


