// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package safety_soc_ctrl_icache_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] q;
  } safety_soc_ctrl_icache_reg2hw_bootaddr_reg_t;

  typedef struct packed {
    logic        q;
  } safety_soc_ctrl_icache_reg2hw_fetchen_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } safety_soc_ctrl_icache_reg2hw_corestatus_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } safety_soc_ctrl_icache_reg2hw_bootmode_reg_t;

  typedef struct packed {
    logic        q;
  } safety_soc_ctrl_icache_reg2hw_icache_enable_prefetch_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } safety_soc_ctrl_icache_reg2hw_icache_flush_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } enable;
    struct packed {
      logic        q;
    } clear_all;
  } safety_soc_ctrl_icache_reg2hw_icache_perfctr_ctrl_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } safety_soc_ctrl_icache_reg2hw_counters_mreg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } safety_soc_ctrl_icache_hw2reg_fetchen_reg_t;

  typedef struct packed {
    logic [1:0]  d;
    logic        de;
  } safety_soc_ctrl_icache_hw2reg_bootmode_reg_t;

  typedef struct packed {
    logic        d;
  } safety_soc_ctrl_icache_hw2reg_icache_flush_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } enable;
    struct packed {
      logic        d;
      logic        de;
    } clear_all;
  } safety_soc_ctrl_icache_hw2reg_icache_perfctr_ctrl_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } safety_soc_ctrl_icache_hw2reg_counters_mreg_t;

  // Register -> HW type
  typedef struct packed {
    safety_soc_ctrl_icache_reg2hw_bootaddr_reg_t bootaddr; // [359:328]
    safety_soc_ctrl_icache_reg2hw_fetchen_reg_t fetchen; // [327:327]
    safety_soc_ctrl_icache_reg2hw_corestatus_reg_t corestatus; // [326:295]
    safety_soc_ctrl_icache_reg2hw_bootmode_reg_t bootmode; // [294:293]
    safety_soc_ctrl_icache_reg2hw_icache_enable_prefetch_reg_t icache_enable_prefetch; // [292:292]
    safety_soc_ctrl_icache_reg2hw_icache_flush_reg_t icache_flush; // [291:290]
    safety_soc_ctrl_icache_reg2hw_icache_perfctr_ctrl_reg_t icache_perfctr_ctrl; // [289:288]
    safety_soc_ctrl_icache_reg2hw_counters_mreg_t [8:0] counters; // [287:0]
  } safety_soc_ctrl_icache_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    safety_soc_ctrl_icache_hw2reg_fetchen_reg_t fetchen; // [306:305]
    safety_soc_ctrl_icache_hw2reg_bootmode_reg_t bootmode; // [304:302]
    safety_soc_ctrl_icache_hw2reg_icache_flush_reg_t icache_flush; // [301:301]
    safety_soc_ctrl_icache_hw2reg_icache_perfctr_ctrl_reg_t icache_perfctr_ctrl; // [300:297]
    safety_soc_ctrl_icache_hw2reg_counters_mreg_t [8:0] counters; // [296:0]
  } safety_soc_ctrl_icache_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_BOOTADDR_OFFSET = 6'h 0;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_FETCHEN_OFFSET = 6'h 4;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_CORESTATUS_OFFSET = 6'h 8;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_BOOTMODE_OFFSET = 6'h c;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_ICACHE_ENABLE_PREFETCH_OFFSET = 6'h 10;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_ICACHE_FLUSH_OFFSET = 6'h 14;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_ICACHE_PERFCTR_CTRL_OFFSET = 6'h 18;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_COUNTERS_0_OFFSET = 6'h 1c;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_COUNTERS_1_OFFSET = 6'h 20;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_COUNTERS_2_OFFSET = 6'h 24;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_COUNTERS_3_OFFSET = 6'h 28;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_COUNTERS_4_OFFSET = 6'h 2c;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_COUNTERS_5_OFFSET = 6'h 30;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_COUNTERS_6_OFFSET = 6'h 34;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_COUNTERS_7_OFFSET = 6'h 38;
  parameter logic [BlockAw-1:0] SAFETY_SOC_CTRL_ICACHE_COUNTERS_8_OFFSET = 6'h 3c;

  // Reset values for hwext registers and their fields
  parameter logic [0:0] SAFETY_SOC_CTRL_ICACHE_ICACHE_FLUSH_RESVAL = 1'h 0;
  parameter logic [0:0] SAFETY_SOC_CTRL_ICACHE_ICACHE_FLUSH_FLUSH_RESVAL = 1'h 0;

  // Register index
  typedef enum int {
    SAFETY_SOC_CTRL_ICACHE_BOOTADDR,
    SAFETY_SOC_CTRL_ICACHE_FETCHEN,
    SAFETY_SOC_CTRL_ICACHE_CORESTATUS,
    SAFETY_SOC_CTRL_ICACHE_BOOTMODE,
    SAFETY_SOC_CTRL_ICACHE_ICACHE_ENABLE_PREFETCH,
    SAFETY_SOC_CTRL_ICACHE_ICACHE_FLUSH,
    SAFETY_SOC_CTRL_ICACHE_ICACHE_PERFCTR_CTRL,
    SAFETY_SOC_CTRL_ICACHE_COUNTERS_0,
    SAFETY_SOC_CTRL_ICACHE_COUNTERS_1,
    SAFETY_SOC_CTRL_ICACHE_COUNTERS_2,
    SAFETY_SOC_CTRL_ICACHE_COUNTERS_3,
    SAFETY_SOC_CTRL_ICACHE_COUNTERS_4,
    SAFETY_SOC_CTRL_ICACHE_COUNTERS_5,
    SAFETY_SOC_CTRL_ICACHE_COUNTERS_6,
    SAFETY_SOC_CTRL_ICACHE_COUNTERS_7,
    SAFETY_SOC_CTRL_ICACHE_COUNTERS_8
  } safety_soc_ctrl_icache_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] SAFETY_SOC_CTRL_ICACHE_PERMIT [16] = '{
    4'b 1111, // index[ 0] SAFETY_SOC_CTRL_ICACHE_BOOTADDR
    4'b 0001, // index[ 1] SAFETY_SOC_CTRL_ICACHE_FETCHEN
    4'b 1111, // index[ 2] SAFETY_SOC_CTRL_ICACHE_CORESTATUS
    4'b 0001, // index[ 3] SAFETY_SOC_CTRL_ICACHE_BOOTMODE
    4'b 0001, // index[ 4] SAFETY_SOC_CTRL_ICACHE_ICACHE_ENABLE_PREFETCH
    4'b 0001, // index[ 5] SAFETY_SOC_CTRL_ICACHE_ICACHE_FLUSH
    4'b 0111, // index[ 6] SAFETY_SOC_CTRL_ICACHE_ICACHE_PERFCTR_CTRL
    4'b 1111, // index[ 7] SAFETY_SOC_CTRL_ICACHE_COUNTERS_0
    4'b 1111, // index[ 8] SAFETY_SOC_CTRL_ICACHE_COUNTERS_1
    4'b 1111, // index[ 9] SAFETY_SOC_CTRL_ICACHE_COUNTERS_2
    4'b 1111, // index[10] SAFETY_SOC_CTRL_ICACHE_COUNTERS_3
    4'b 1111, // index[11] SAFETY_SOC_CTRL_ICACHE_COUNTERS_4
    4'b 1111, // index[12] SAFETY_SOC_CTRL_ICACHE_COUNTERS_5
    4'b 1111, // index[13] SAFETY_SOC_CTRL_ICACHE_COUNTERS_6
    4'b 1111, // index[14] SAFETY_SOC_CTRL_ICACHE_COUNTERS_7
    4'b 1111  // index[15] SAFETY_SOC_CTRL_ICACHE_COUNTERS_8
  };

endpackage

