PULP_APP = runtime_timer_freerunning
PULP_APP_FC_SRCS = runtime_timer_freerunning.c
PULP_APP_HOST_SRCS = runtime_timer_freerunning.c
PULP_CFLAGS = -O3 -g

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk

