PULP_APP = runtime_bus_err
PULP_APP_FC_SRCS = runtime_bus_err.c
PULP_APP_HOST_SRCS = runtime_bus_err.c
PULP_APP_ASM_SRCS = handler.S
PULP_CFLAGS = -O3 -g -I../runtime_shared/include

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk

