PULP_APP = runtime_chs_uart
PULP_APP_FC_SRCS = uart.c runtime_chs_uart.c
PULP_APP_HOST_SRCS = uart.c runtime_chs_uart.c
PULP_CFLAGS = -O0 -g -Iinclude

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk

